# Generated by Django 2.2.10 on 2020-07-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0009_requeued_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='label',
            field=models.CharField(blank=True, default='', help_text='Human readable template name', max_length=128, verbose_name='Label'),
        ),
    ]
