# Generated by Django 3.1.7 on 2022-03-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0011_models_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='headers',
            field=models.JSONField(blank=True, null=True, verbose_name='Headers'),
        ),
        migrations.AlterField(
            model_name='email',
            name='headers',
            field=models.JSONField(blank=True, null=True, verbose_name='Headers'),
        ),
    ]
