# Generated by Django 3.2.15 on 2022-09-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post_office", "0011_models_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="headers",
            field=models.JSONField(blank=True, null=True, verbose_name="Headers"),
        ),
        migrations.AlterField(
            model_name="email",
            name="context",
            field=models.JSONField(blank=True, null=True, verbose_name="Context"),
        ),
        migrations.AlterField(
            model_name="email",
            name="headers",
            field=models.JSONField(blank=True, null=True, verbose_name="Headers"),
        ),
    ]
