# Generated by Django 3.2.13 on 2022-07-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0011_models_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'sent'), (1, 'failed'), (2, 'queued'), (3, 'requeued'), (4, 'draft')], db_index=True, null=True, verbose_name='Status'),
        ),
    ]
