# Generated by Django 5.1 on 2025-05-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('post_office', '0012_alter_attachment_file_storage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['name', 'language'], name='post_office_name_74d644_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['name', 'language', 'default_template'], name='post_office_name_0a6613_idx'),
        ),
    ]
