# Generated by Django 5.2.4 on 2025-07-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0012_alter_attachment_file_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='recipient_delivery_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Accepted'), (20, 'Delivered'), (30, 'Deferred'), (40, 'Soft Bounce'), (50, 'Hard Bounce'), (60, 'Rejected'), (70, 'Open'), (80, 'Click'), (90, 'Spam Complaint'), (100, 'Unsubscribed')], null=True, verbose_name='Recipient Delivery Status'),
        ),
        migrations.AddField(
            model_name='log',
            name='recipient_delivery_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Accepted'), (20, 'Delivered'), (30, 'Deferred'), (40, 'Soft Bounce'), (50, 'Hard Bounce'), (60, 'Rejected'), (70, 'Open'), (80, 'Click'), (90, 'Spam Complaint'), (100, 'Unsubscribed')], null=True, verbose_name='Recipient Delivery Status'),
        ),
    ]
