# Generated by Django 4.2.4 on 2025-08-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_office", "0013_email_recipient_delivery_status_alter_log_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="headers",
            field=models.JSONField(blank=True, null=True, verbose_name="Headers"),
        ),
        migrations.AlterField(
            model_name="email",
            name="context",
            field=models.JSONField(blank=True, null=True, verbose_name="Context"),
        ),
        migrations.AlterField(
            model_name="email",
            name="headers",
            field=models.JSONField(blank=True, null=True, verbose_name="Headers"),
        ),
    ]
