# Generated by Django 5.1 on 2025-05-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('post_office', '0013_emailtemplate_post_office_name_74d644_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='example_context',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Example Context'),
        ),
    ]
